### ISSUE TITLE
Update readme with install instructions for Mac OSX

### ISSUE THREAD

**Issue by JonathanFager** [BrewBlox/brewblox-ui#996] opened 2019-11-01 13:12 UTC
**Is your feature request related to a problem? Please describe.**
Cannot install Brewblox UI for development and generall funsies on Mac OSX

**Describe the solution you'd like**
Would like the "please contact us for detailed explanation" to be written out.

**Comment by steersbob** [comment] 2019-11-01 14:28
Right now I don't have direct access to a Mac, and can only guess at which workarounds are required.
If you want, I can send you an invite to our Slack channel, and help identify what's going wrong.

Edit: to avoid being cryptic, the things I suspect may go wrong are:
- Is docker / docker-compose available in path?
- Docker port publishing
- We run the mDNS service using `network_mode: host`. I believe docker for mac handles networking here subtly different. The good news is that you don't really need it for UI development.
- We use some bash tools during the backend setup. Some may not be available on mac.
- Automatic generation of self-signed SSL cert if it doesn't exist. Last I heard, mac did not have OpenSSL installed. You'll likely have to create your own cert file, and manually place it in the dir.

**Comment by JonathanFager** [comment] 2019-11-01 17:44
The error I'm getting is the following: 
(node:12272) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

So, being a total docker-noob, I'm guessing its the latter of your suspicions. However, I don't know how to remedy this.
Cheers

**Comment by steersbob** [comment] 2019-11-01 17:49
That's a warning. Does it stop execution of `npm start`?

It's caused by us setting `NODE_TLS_REJECT_UNAUTHORIZED=false` in a setup script, because otherwise the self-signed dev certificate causes an error.

**Comment by JonathanFager** [comment] 2019-11-01 17:50
Retrying after error, Error: write EPROTO 4578276800:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 80
then repeats this until exhaust.

**Comment by steersbob** [comment] 2019-11-01 17:55
Is there sensible content in `dev/traefik/brewblox.cnf`? Should be an ini style file.

For example, mine starts with:
```
#
# OpenSSL example configuration file.
# This is mostly being used for generation of certificate requests.
#
```

If it's empty, or just contains some error, you should generate your own certificate https://support.apple.com/guide/keychain-access/create-self-signed-certificates-kyca8916/mac and copy the .crt / .key files to `dev/traefik`.

The extensions can be slightly different. The .crt file should start with `-----BEGIN CERTIFICATE-----` and the .key file with `-----BEGIN PRIVATE KEY-----`

**Comment by JonathanFager** [comment] 2019-11-01 18:04
Thank you Bob. Will try this out!

**Comment by steersbob** [comment] 2020-04-16 17:28
@JonathanFager we moved cert generation into a docker container for compatibility.
Were there any other problems you encountered? Otherwise closing this issue as resolved.

**Closed as completed** 2020-04-18 14:51 UTC
